### ISSUE TITLE
Support Conditional CRUD operations

### ISSUE THREAD

**Issue by rsmayda** [awslabs/fhir-works-on-aws-persistence-ddb#10]
FHIR does have support for conditional operations **but** it is currently in **trial use** only. This issue will serve as a tracker on our progress to support this new functionality. Also if this is a feature you'd like please let us know

FHIR spec for context: https://www.hl7.org/fhir/http.html#cond-update

A/C:

- Add functionality
- Update integration test
- Update deploy package to support it

**Comment by hemag24** [comment]
We are working on FHIR(Fast Healthcare Interoperability Resources).
We have followed “FHIR works on AWS” and deployed the Cloud Formation template given by AWS in our AWS environment.Following is the template that we have deployed.

https://docs.aws.amazon.com/solutions/latest/fhir-works-on-aws/aws-cloudformation-template.html

Requirement : we want to maintain client specific/customized ids as primary key in the server.
Problem : server not allowing us to override or maintain client specific (customized) ids as primary key. Infact, in the runtime, it is generating its own ids and ignoring the ids provided by us.
Could you please let us know if there is any way to post the FHIR resource with client specific ids into Dynamo DB.

**Comment by SG-Sivaram-Movva** [comment]
> FHIR does have support for conditional operations **but** it is currently in **trial use** only. This issue will serve as a tracker on our progress to support this new functionality. Also if this is a feature you'd like please let us know
> 
> FHIR spec for context: https://www.hl7.org/fhir/http.html#cond-update
> 
> A/C:
> 
> * Add functionality
> * Update integration test
> * Update deploy package to support it

Yes, we are looking for this feature.

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
