### ISSUE TITLE
[Feature Request] Need New documentStatus for Old Versions of Resources and Reverted Resources

### ISSUE THREAD

**Issue by Nathan-acoustic** [awslabs/fhir-works-on-aws-persistence-ddb#111]
**Is your feature request related to a problem? Please describe.**
If a resource is updated with a new version, the old version is marked as 'DELETED'. This makes the reference to the old version points to an invalid ('DELETED') resource.

Sometimes we need to do a 'reverting' for the resources added to the dynamodb, but we can not do a hard delete or mark it as 'DELETED' because there might be a reference pointing to it. We would like a new status (e.g. 'REVERTED')

**Describe the solution you'd like**
We would like to have a new status (e.g. OLD, STALE, OUT_OF_DATE, etc) for old versions of resources.
when a resource is updated with a new version, the old version is updated to this new status (in dynamoDbBundleService).

After reverting, the reverted version could be the only one for the resource. We would like to make the new status (e.g. 'REVERTED') user-readable (in dynamoDbHelper.getMostRecentUserReadableResource())

We would like to have resources with these new statuses indexed in ES by ddbToESSync.

**Describe alternatives you've considered**

**Additional context**

**Comment by SanketD92** [comment]
Thank you for creating this feature request. We've added it to our team's backlog. Stay tuned!

**Comment by Zambonilli** [comment]
@Nathan-acoustic I have an open PR to address the non-standard DELETE behavior. I implementing the delete resource instance version with an internal code system and code instead of a new documentStatus enum value.

https://github.com/awslabs/fhir-works-on-aws-deployment/issues/714

**Comment by nguyen102** [comment]
Thanks for reaching out about this topic. Please note that we may not take immediate action on this issue and it may be left open as we evaluate demand and support for this issue. Updates will be provide as they become available.

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
