### ISSUE TITLE
[Feature Request] Keep Track of Resource Count in DDB by Resource Type

### ISSUE THREAD

**Issue by Nathan-acoustic** [awslabs/fhir-works-on-aws-persistence-ddb#114]
**Is your feature request related to a problem? Please describe.**
We sync resources from dynamodb to elasticsearch, but errors can occur in the sync process. We want to create a report about the resource count in DDB and ES to check whether resource counts in ES match those in DDB.
To get the counts in ddb by scanning the table is not feasible for production; if we use DynamoDB stream to call a Lambda function to update the counts, it is hard to keep the results accurate, since errors can happen in the step of updating the counts.

**Describe the solution you'd like**
We would like to add some logic to update the resource counts and store them somewhere (e.g. a new ddb table) when a resource is created or deleted, and updating counts must be in the same transaction as creating/deleting resources.

**Describe alternatives you've considered**
switch to other databases that support queries with aggregation

**Additional context**

**Comment by SanketD92** [comment]
Thank you for creating this feature request. We've added it to our team's backlog. Stay tuned!

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
