### ISSUE TITLE
fhir-works-on-aws-deployment listed as dependency in the readme

### ISSUE THREAD

**Issue by ilyash-b** [awslabs/fhir-works-on-aws-persistence-ddb#133]
https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/9887fb70032545ef40d2ae6910a32b57694017c4/README.md?plain=1#L29

but I couldn't find any reference to fhir-works-on-aws-deployment except for the readme.

Is it really a dependency?

**Comment by Bingjiling** [comment]
Hi @ilyash-b , 

You brought up a good point here. The deployment package is a dependency in a way that the persistence package need to be deployed using the deployment package. If you're planning to use the persistence package by itself or deployed through other mechanism, then the deployment package is not needed. 

Hope this helps. 

Thanks,
Yanyu

**Comment by ilyash-b** [comment]
I see. I think the wording can be improved then. "deployed by" would be much better than "depends on". Like a library does not depend on the program using it; Like a software does not depend on IaaC that deploys it.

**Comment by nguyen102** [comment]
https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/pull/134
PR for the fix

**Comment by nguyen102** [comment]
PR merged
