### ISSUE TITLE
[Bug] Response Resource of creating Binary resource doesn't contain custom fields with HAPI FHIR library

### ISSUE THREAD

**Issue by lquanx** [awslabs/fhir-works-on-aws-persistence-ddb#149]
**Describe the bug**
`PresignedPutUrl` field in Binary resource is not complied with FHIR spec, hence a popular FHIR library [HAPI FHIR](https://hapifhir.io/) doesn't return the response Binary with `PresignedPutUrl` field while creating a Binary Resource. 

Of course, I can reach out to HAPI FHIR team to support custom Resource fields. They may add the support. However, since custom fields are not aligned with FHIR spec, I think it would be better to fix the issue in this repo.

One possible solution is [this PR](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/pull/151). In the PR, I moved the custom fields to `_data.extension`. You may already know the parent of Binary is Resource, meaning we cannot add extensions directly to the Binary resource. That's why I use the field extension.

**To Reproduce**
1. Use HAPI FHIR client to create Binary resource
```
        Binary binary = new Binary();
        binary.setContentType("application/pdf");
        MethodOutcome response = this.hapiFhirClient.create()
                .resource(binary)
                .encodedJson()
                .execute();
        Binary responseResource = (Binary) response.getResource();
```

**Expected behavior**
`responseResource` has the value of `PresignedPutUrl`

**Additional context**

**Comment by ssvegaraju** [comment]
HI @lquanx, thanks for bringing this up! I'll take this back to the team to discuss our options; Unfortunately this change would require an update to some of the other packages that are part of FWoA, so the PR you created may not make it through without additional work. I will comment here when I have an update for you!

**Comment by lquanx** [comment]
Thanks @ssvegaraju

**Comment by ssvegaraju** [comment]
Hey @lquanx, small update for you: After discussing with the team, we realized that this update would be a potentially breaking change, and would still not be quite compliant with the FHIR spec for Binary resources. We're going to take a look into other options (maybe even to embrace this breaking change) to see if we can just make our Binary implementation compliant around the limitations of 6MB upload for Lambda and 10MB for API Gateway. We will keep you updated on our decision.

Thanks again,
Sukeerth

**Comment by lquanx** [comment]
That makes sense. Thanks !

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
