### ISSUE TITLE
[Bug] Back-to-back batch updates of the same record creates duplicate records

### ISSUE THREAD

**Issue by DJK-Cognosante** [awslabs/fhir-works-on-aws-persistence-ddb#152]
**Describe the bug**
Sending a batch update with a PUT to a specific practitioner, and then _after_ the first batch resolves and returns a response, immediately sending another batch update containing a PUT to that same specific practitioner, creates a duplicate record rather than updating. 

- Both records use the same ID, and only the latest version is returned when calling GET against that practitioner.
- When running a search based on e.g. name or NPI, both versions of the record are returned.
- Calling DELETE against the record will only delete the latest version, but the previous version is left ACTIVE in DynamoDB, and therefore still returns in the search results.
- Calling DELETE again to try and delete the still-active record returns 404 Not Found.

**To Reproduce**
1. Create a new practitioner record with a unique name.
2. Send a batch request to fhirworks containing a PUT request to `/Practitioner/${id of record you just created}`
3. As soon as that request resolves, send it again. You have to send it _after_ the previous request resolves, but before DynamoDB's commit window so the changes aren't quite persisted to the DB or the search service yet (admittedly I don't know much about how it works under the hood; this is just my understanding based on preliminary poking around).
4. Perform a search against the practitioner endpoint based around the practitioner's name.
5. You will see two records in the search results with the same ID.
6. Send a DELETE request against the practitioner and re-run the search.
7. You will now see one record in the search results.
8. Send a GET request to the practitioner endpoint, using the ID of the practitioner.
9. You will get 404 Not Found, despite that practitioner appearing in the search results.

**Expected behavior**
Successive PUT requests to the same endpoint (batched or not) should be queued to run sequentially, and await the DynamoDB and/or Elasticsearch commit time to ensure duplicate records are not created.

**Versions (please complete the following information):**
 - Release Version installed: 4.3.1

**Additional context**
We are working on a bulk import process, and our sample file contained the same ~50 records repeated over and over again just to quickly fill out test data. The records were grouped up into chunks of 10-20 and then imported, making sure that each individual request contains no duplicates, and that each request is awaited and fully resolved before doing the next one. We now have 18000+ duplicate records in our test system that we cannot delete by any means.

For the time being, as a workaround, we've had to simply state that all import files must be manually checked for duplicate identifiers before being imported, to make 100% sure that the same record isn't updated twice in too short of a timespan. This obviously isn't ideal as some of the files contain millions of records.

**Comment by DJK-Cognosante** [comment]
Okay so I can confirm that this doesn't have to be back-to-back requests. These two resources were processed about 90 minutes apart. The request in that batch was a PUT against that resource's ID. It created a new version number of that record at the same ID, but then failed to mark the previous version inactive, so they both return in the search results. There's no way AFAIK to get delete the first version. DELETE will only get rid of v2, and subsequent DELETEs will 404.

![image](https://user-images.githubusercontent.com/92823292/183463513-bafc6462-7685-4b61-8d81-9195080c1608.png)

**Comment by ssvegaraju** [comment]
Hey @DJK-Cognosante, thanks for catching this! For some context: We used versioned resources when storing resources in FWoA: So PUT operations should just bump the vid of the resource (or create it if upsert is enabled). Similarly, when deleting we just mark an internal field to signal that the resource has been deleted to mimic soft deletion. This can be changed by configuring the `esHardDelete` config option during deployment. For this particular bug however, I have added this in our backlog to investigate! Does this also occur outside of batch transactions (i.e. PUTting a resource that has just been created creating a new resource)?

**Comment by DJK-Cognosante** [comment]
@ssvegaraju we're still investigating the details internally. It appears to happen inconsistently. My current theory is that it only happens under heavy load. What appears to be happening is the DDB resource gets marked as deleted, but that update isn't pushed to the opensearch server, so those versions still return in the search results. I'm guessing that under particularly heavy load, the lambda responsible for updating the opensearch index gets overwhelmed and stops responding.

**Comment by ssvegaraju** [comment]
That makes sense! There is a 24 hour limit on ddb streams (unfortunately this isn't configurable), so under heavy load transactions that have been queued for longer than that period of time may be lost before being written to opensearch. One possible solution would be to raise some of the configuration settings for the `ddbToEs` lambda: either upping provisioned concurrency or increasing the batch size.

**Comment by DJK-Cognosante** [comment]
Sorry if this is a dumb question @ssvegaraju, but I've noticed in my cleanup script that sending a large volume of requests in a short time to the opensearch API will eventually result in 429 Too Many Requests.

Is it possible that this is what's happening here? Could the opensearch API be rejecting requests from the ddbToEs lambda after a certain number of requests? I'm not sure how these services are configured, and if they're able to ignore the 429 rate limit for other AWS services, but it's just a thought I had last night.

**Comment by ssvegaraju** [comment]
That's a good question @DJK-Cognosante! I know we construct the Client to interact with opensearch [here](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/ddbToEs/ddbToEsHelper.ts#L38), but I don't see any special configurations that might prevent 429s. I do think that the Lambda function is rate limited to avoid running into that error, but this is worth checking through the CloudWatch logs/metrics to double check.

**Comment by rsmayda** [comment]
Another important callout is that OpenSearch is scaled to whatever you decide to install/use. So for your production installations we recommend that you stress test OpenSearch to handle your expected load. 

Here is the CDK where you can change it to meet your needs: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/lib/elasticsearch.ts#L285

i.e. if you are getting 429s OpenSearch is most likely not scaled enough

**Comment by rsmayda** [comment]
Also @DJK-Cognosante could you provide a sample of what your batch request looks like? (The json that is submitted to the FHIR server). For both request 1 and request 2

Also could you describe the amount of load the FHIR server is seeing?

**Comment by DJK-Cognosante** [comment]
@rsmayda I'd have to get those sample JSON files you you in the AM.

We've been told that the production files we are targeting will contain up to 1.5 million records, so we've been producing sample files of the same X many records repeated over and over to get to 1.5 million records. The production files are not guaranteed to be duplicate-free, so this is an exaggerated, but not irrelevant use case.

Our import process right now loads 15 records per batch, 2 batches at once (these values are configurable). Each batch performs a single search for all identifiers in that batch, then pairs those previous versions up with their corresponding records to get the FHIR ID that each record is updating, and then sends a single batch update for all 15 records. So in total, about 4 FHIR requests in the air "at once" (the timing isn't exactly at once, but you get the idea), about 50k times. The entire process takes about 3 days. We start seeing duplicates a couple of hours in.

We've done this process a couple of times with a couple of different sample files. If OpenSearch scales itself after stress testing, then I doubt it's OpenSearch returning 429s during the import process. Come to think of it, it's quite strange that the newly-imported records are being added to OpenSearch, but it's only the old records that aren't being updated to be marked as deleted. I don't think it's the ddbToEs lambda or OpenSearch to blame if that's the case.

I'll get you those test documents in the morning and keep you posted if I find anything else. My next steps right now are to clean the duplicates out of our QA environment and then try the file again using transaction instead of batch. Our suspicion is that, because [DDB doesn't support updating records via BatchWriteItem](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html), the update of old versions to DELETED is being dropped there, and perhaps transaction (which uses TransactWriteItems under-the-hood) wouldn't have this problem.

**Comment by Bingjiling** [comment]
Hi @DJK-Cognosante, 

Are you using batch request type in bundles? Given you are loading 15 records per request, you can try using transaction request type in bundle instead. 

Transaction request type ensures each bundle request either succeed or fail as a whole and leaves DDB in a clean and consistent state. Although transaction has a lower limit on records per request and is less performant compared to batch, I think it is a good choice for your workflow as 15 is under the limit for transaction and it saves manual de-duplicate work down the line. 

Here's an [example](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/caaf57def2302509d36ad68ef9fc364a29211633/integration-tests/createGroupMembersBundle.json) transaction request body from integ tests. Note the 'type' field is set to 'transaction' instead of 'batch'. 

Thanks,
Yanyu

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:aws-security@amazon.com) (mailto:[security@amazon.com](mailto:security@amazon.com)). If you are new to this solution, we advise you to explore using HealthLake (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [[fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com)](mailto:[fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com)) or contact your AWS Account team.
