### ISSUE TITLE
About Conditional Create at fhir-works-on-aws

### ISSUE THREAD

**Issue by fhir-works-dev01** [awslabs/fhir-works-on-aws-persistence-ddb#162]
We have deployed and verified fhir-works-on-aws at the following URL. 

https://github.com/awslabs/fhir-works-on-aws-deployment/archive/refs/tags/v5.1.0.zip 

Is Conditional Create supported in this version?
And if it is supported, how do I configure it to enable it?

 It would be helpful if you could guide me.

**Comment by Bingjiling** [comment]
Hi,

Appreciate the feedback, but this isn't something we are considering at this time. If more feedback comes on this topic it may be something we could consider at that time, but there are currently no plans.

Thanks,
Yanyu

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:aws-security@amazon.com)](mailto:[security@amazon.com (mailto:security@amazon.com)). If you are new to this solution, we advise you to explore using HealthLake (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [[fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com)](mailto:[fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com)) or contact your AWS Account team.
