### ISSUE TITLE
Return error if createResource has a duplicate id specified

### ISSUE THREAD

**Issue by arthuston** [awslabs/fhir-works-on-aws-persistence-ddb#17]
The fhir-works-on-aws-persistence dynamoDbDataService createResource function allows specifying a database id (for DynamoDB, a generated UUID), but it does not check to see if the ID has already been used. It should return an error. We are using the internal API during uploads instead of going through the FHIR API. The createResource method is defined in https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/a8cb6fa3f8f8ecd3e3875dc366fd8cdda43dd8db/src/dataServices/dynamoDbDataService.ts#L68.

Acceptance criteria:

Writing a record using the fhir-works-on-aws-persistencedynamoDbDataService createResource returns an error if the id is specified and it already exists in the database.

**Comment by rsmayda** [comment]
Looking at the FHIR spec more closely; it looks like we actually want to ignore the 'id' and meta data field for `create`:

> If an id is provided, the server SHALL ignore it. [create spec](https://www.hl7.org/fhir/http.html#create)

Then the create a resource with an 'id' functionality should be moved to `update` as `updateCreate`

**Comment by rsmayda** [comment]
Closing this issues as you can no longer use `create` to `updateCreate`: https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/dataServices/dynamoDbDataService.ts#L106
