### ISSUE TITLE
Detect all invalid resources instead of failing in Elastic Search.

### ISSUE THREAD

**Issue by arthuston** [awslabs/fhir-works-on-aws-persistence-ddb#18]
Invalid resources are being created in DynamoDB and then failing in Elastic Search:

For example, money types like "net": 12345 are allowed when "net": { "value": 12345, "currency": "USD"} are expected. This stores the object in DynamoDB but fails during elastic search.

This occurs despite the schema validator specifying that Money is a dictionary.

AC:

Entering an invalid object should fail.

**Comment by rsmayda** [comment]
Did some digging and found this: When a new object is added to an ES index all of the params of that object are dynamically mapped to an ES data type. Since `net` comes in as a string first, all future `net` must be a string or you will get this behavior. This failure causes the DDB & ES to become out of sync.

**Comment by rsmayda** [comment]
As noted in https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/issues/46 "Failed records are not moved to DLQ and no logs are available. We need to add logs/DLQ to find out these type of bugs."

**Comment by PrimKruskal** [comment]
@rsmayda  Is development happening for this bug ?  We have quite few scenarios not working due to data conversion issues.    Is there plans to introduce mapping templates rather than ES to determine format dynamically ? Do you require support to fix this functionality quickly ?

**Comment by rsmayda** [comment]
We will start working on fixing this bug in early April. We plan to address the identification of this issue by putting in a DLQ and Cloudwatch Alarms. As for the static mapping, we do not currently have this on our roadmap, but would love to discuss more in our next stand-up.

**Comment by rsmayda** [comment]
We are now logging failures into a DLQ and improved logging to identify the problematic resources
