### ISSUE TITLE
Maintain referential integrity for creates

### ISSUE THREAD

**Issue by arthuston** [awslabs/fhir-works-on-aws-persistence-ddb#19]
Resources can be created with missing References that should return an error. They should return a  HTTP 422 Unprocessable Entity.

For example, use Postman to create a Patient using the following HTTP body:
```
{
    "active": true,
    "maritalStatus": "U",
    "resourceType": "Patient",
    "identifier": [
        {
            "period": {
                "start": "2011-03-29T05:05:56.968Z",
                "end": "2025-02-07T13:28:17-05:00"
            },
            "system": "http://www.acmehosp.com/patients",
            "type": "TAX",
            "value": "P7822793277",
            "use": "usual"
        }
    ],
    "meta": {
        "lastUpdated": "2020-09-22T16:32:31.155Z",
        "versionId": "1"
    },
    "managingOrganization": {
        "reference": "Organization/1"
    },
    "id": "8adfb20d-37b4-471c-ae59-39b558606aa0",
    "name": [
        {
            "given": [
                "Hosea"
            ],
            "text": "Hosea Grady",
            "family": "Grady",
            "suffix": [
                "IV"
            ],
            "use": "official",
            "prefix": []
        }
    ],
    "gender": "other"
}
```
The organization id (1) is invalid. The API returns 201 (Created), it should return 422.

Use the Organization GET API with the organization id of 1. It returns 404, indicating that the Organization is missing.

For an example of the correct functionality, use the http://hapi.fhir.org/create test page.

AC:

Creating any resource with a reference to  missing resource  returns 422 instead of success.

**Comment by rsmayda** [comment]
This is a great enhancement! Checking out the [FHIR spec](https://www.hl7.org/fhir/http.html#create) I don't see 'hard' referential requirements. As mentioned with issue https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/issues/20 We are open to implementation ideas, leading candidates so far include DynamoDB indexing

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
