### ISSUE TITLE
Maintain referential integrity for deletes

### ISSUE THREAD

**Issue by arthuston** [awslabs/fhir-works-on-aws-persistence-ddb#20]
Resources can be deleted when they are referenced with other resources. They should return a  HTTP 422 Unprocessable Entity.

For example, use Postman to create this Organization:
```
{
    "resourceType": "Organization",
    "identifier": [
        {
            "value": "Gastro",
            "system": "http://www.acme.org.au/units"
        }
    ],
    "meta": {
        "lastUpdated": "2020-09-18T20:10:46.184Z",
        "versionId": "1"
    },
    "telecom": [
        {
            "value": "+1 555 234 3523",
            "use": "mobile",
            "system": "phone"
        },
        {
            "value": "gastro@acme.org",
            "use": "work",
            "system": "email"
        }
    ],
    "text": {
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n      \n      <p>Gastroenterology @ Acme Hospital. ph: +1 555 234 3523, email: \n        <a href=\"mailto:gastro@acme.org\">gastro@acme.org</a>\n      </p>\n    \n    </div>",
        "status": "generated"
    },
    "name": "Gastroenterology"
}
```
Note the OBSERVATION_ID and use it to create this Patient in Postman:
```
{
    "active": true,
    "maritalStatus": "U",
    "resourceType": "Patient",
    "identifier": [
        {
            "period": {
                "start": "2011-03-29T05:05:56.968Z",
                "end": "2025-02-07T13:28:17-05:00"
            },
            "system": "http://www.acmehosp.com/patients",
            "type": "TAX",
            "value": "P7822793277",
            "use": "usual"
        }
    ],
    "meta": {
        "lastUpdated": "2020-09-22T16:32:31.155Z",
        "versionId": "1"
    },
    "managingOrganization": {
        "reference": "Organization/<ORGANIZATION_ID>"
    },
    "id": "8adfb20d-37b4-471c-ae59-39b558606aa0",
    "name": [
        {
            "given": [
                "Hosea"
            ],
            "text": "Hosea Grady",
            "family": "Grady",
            "suffix": [
                "IV"
            ],
            "use": "official",
            "prefix": []
        }
    ],
    "gender": "other"
}
```
The Patient is created with a reference to Organization/<ORGANIZATION_ID>.

Use Postman to delete this Organization <ORGANIZATION_ID>

It returns 200, indicating the Organization was deleted. It should return 409.

For an example of the correct functionality, use the http://hapi.fhir.org/create and related test pages.

Acceptance critiera:

- Deleting a resource that is referenced in another resource returns 409 instead of.success.

**Comment by rsmayda** [comment]
Thanks for the enhancement request!

> If the server refuses to delete a resource because of reasons specific to that resource, such as referential integrity, it should return the 409 Conflict status code. Note that the servers MAY choose to enforce business rules regarding deletion of resources that are being referenced by other resources, but they also MAY NOT do so. [delete spec](https://www.hl7.org/fhir/http.html#delete)

We are open to implementation ideas -- at a quick pass adding DynamoDB keys/tables to store this referential information, or perhaps just adding a new index to the existing table.

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
