### ISSUE TITLE
Add Profile Support

### ISSUE THREAD

**Issue by arthuston** [awslabs/fhir-works-on-aws-persistence-ddb#23]
Add Profile support for:

- US Core
- Carin-BB
- DaVinci PDEX
- DaVinci PDEX Formulary
- DaVinci PDEX Plan Net.

- Patient API
-- Patient API - General
--- C4BB Patient
-- Patient API - Claims & Encounters
--- C4BB Coverage
--- C4BB ExplanationOfBenefit Inpatient Institutional
--- C4BB ExplanationOfBenefit Outpatient Institutional
--- C4BB ExplanationOfBenefit Pharmacy
--- C4BB ExplanationOfBenefit Professional NonClinician
--- Location
--- C4BB Organization
--- C4BB Practitioner
--- US Core PractitionerRole Profile
--- Patient API - Clinical
--- US Core AllergyIntolerance Profile
--- US Core CarePlan Profile
--- US Core CareTeam Profile
--- US Core Condition Profile
--- PDex Device
--- US Core DiagnosticReport Profile for Laboratory Results Reporting
--- US Core DiagnosticReport Profile for Report and Note exchange
--- US Core Laboratory Result Observation Profile
--- US Core DocumentReference Profile
--- US Core Encounter Profile
--- US Core Goal Profile
--- US Core Immunization Profile
--- US Core Medication Profile
--- US Core Medication Request Profile
--- PDEX MedicationDispense
--- US Core Medication Profile
--- US Core MedicationRequest Profile
--- US Core Pediatric BMI for Age Observation Profile
--- US Core Pediatric Head Occipital-frontal Circumference Percentile Profile
--- US Core Pediatric Head Occipital-frontal Circumference Percentile Profile
--- US Core Pediatric Weight for Height Observation Profile
--- US Core Pulse Oximetry Profile
--- US Core Smoking Status Observation Profile
--- US Core Procedure Profile
- PdexEntitySourceProvenance
- PDex Source Provenance
- Vital Signs Profile
- Interoperability API
- Interoperability - Drug Formulary
- Coverage Plan
- Formulary Drug (extends MedicationKnowledge)
- Interoperability - Provider Directory
- PlannetEndpoint
- PlannetHealthcareService
- PlannetInsurancePlan
- PlannetLocation
- PlannetOrganizationAffiliation
- PlannetPractitionerRole

**Comment by nguyen102** [comment]
Thanks for the suggestion! Making it easy to add support for more profiles is something we're currently looking into. We will publish more details on how to manually add support for more profiles in the future.

However, the current approach to adding profile support is:
1. Add the JSON schema for your new profile and have the [validator](https://github.com/awslabs/fhir-works-on-aws-routing/blob/496350f499776d5ebec6a6d1a601e7def26178a3/src/router/validation/validator.ts) reference that schema. This will allow the routing layer to correctly validate resources that is specified in the new profile.
2. For a POST request, once a resource has been validated, we add some meta data to the resource and write it to DynamoDB. If additional logic is required to handle the resource besides what is already currently done, you can add the resource to [config](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/000fb80aff9f49ce92a54474ca61d3888b59b9da/src/config.ts#L75) and point it to a new `persistence` package. The new `persistence` package can implement new logic to handle that resource.

**Comment by rsmayda** [comment]
Added profile support is released on how to use it please see this file: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md
