### ISSUE TITLE
Add additional attribute for internal index

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-persistence-ddb#43]
Add an attribute for an internal index with a global secondary index across it. The need is so that there can be an additional lookup outside of Elastic Search. The local index is with in the JSON and if this index could be sent and stored within this new index attribute our process from Flink could do a direct lookup through DynamoDb thus helping with performance.

**Comment by rsmayda** [comment]
We should talk more about this. I cannot tell if this is generic enough to keep in 'mainline' or if this should be custom code. Let circle up in our next 1-1 and update the issue here
