### ISSUE TITLE
DynamoDB streams to ES Issue - Not able to handle different date formats.

### ISSUE THREAD

**Issue by aravindatcts** [awslabs/fhir-works-on-aws-persistence-ddb#46]
Resources are not getting loaded into Elasticsearch from DynamoDB streams, if same date field is having different date time formats.  As per HL7, date can be any of following formats - "2020", "2021-01" or "1905-08-23", "2015-02-07T13:28:17-05:00 or 2017-01-01T00:00:00.000Z".  

For example from FHIR website example for allergyIntolerance, 
```json
manifestation": [
        {
          "coding": [... ],
      "description": "Challenge Protocol. Severe reaction to subcutaneous cashew extract. Epinephrine administered",
      **"onset": "2012-06-12",**
      "severity": "severe",
      "exposureRoute": {
        "coding": [
         ...
        ]
      }
    },
    {
      "manifestation": [
        {
          "coding": []
        }
      ],
      **"onset": "2004",**
```
Here Onset is having two different formats,  so when ES builds index for Onset field it is considered as dateTime and for next Onset it is considering it to be Text/String.  So records are not getting loaded into ES. 

Note: Failed records are not moved to DLQ and no logs are available.  We need to add logs/DLQ to find out these type of bugs.

**Comment by rsmayda** [comment]
Thanks for opening this issue! This seems to be the same as #18. I added some context to that issue. For ease of use & tracking I suggest we close this issue in favor of #18. Let us know your thoughts!
