### ISSUE TITLE
Throw error if resource found does not match resourceID

### ISSUE THREAD

**Issue by emilhdiaz** [awslabs/fhir-works-on-aws-persistence-ddb#50]
**Defect**

Currently `DynamoDbHelper` does not validate that the `resourceType` of the DynamoDB record retrieved via `getMostRecentResource()` or `getMostRecentValidResource()` matches the `resourceType` passed into those functions. This allows an API client to request resources of a different FHIR resource type through the wrong URLs. 

**Actual**
A Patient record with `id=8a9f93c9-0f37-4a98-bb55-76992774a98b` can be retrieved through the URL `/ExplanationOfBenefits/8a9f93c9-0f37-4a98-bb55-76992774a98b`. 

**Expected**
The above Patient should only be accessible via the URL `/Patient/8a9f93c9-0f37-4a98-bb55-76992774a98b`. Additionally, the URL `/ExplanationOfBenefits/8a9f93c9-0f37-4a98-bb55-76992774a98b`, should return an HTTP 404 - Not Found.

**Comment by rsmayda** [comment]
+1 great find - you are right. We will be working on this bug in the next two weeks
