### ISSUE TITLE
[updateCreate] Support update operation creating initial version of resource

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-persistence-ddb#55]
Hi AWS team,
If we try to create a new resource via an update operation (as per https://www.hl7.org/fhir/http.html#update), the current code doesn't support this.
Previously we were doing this via a create operation but the code changes on Feb 5th (4f433d2eacdd81c25bdc6e5a2d5e9ea755a33204) now prevent us from doing this!

I'd have though it'd be relatively easy to trap the resource not found case in
https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/eefb657b0639c10910ada404f91d6418926b339c/src/dataServices/dynamoDbDataService.ts#L149
and then invoke the create operation?
Many thanks,
Allan

**Comment by nguyen102** [comment]
Hi Allan,
You're correct, we do not support Update as Create. Is that the feature you're looking for? 

The commit that you mentioned https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/commit/4f433d2eacdd81c25bdc6e5a2d5e9ea755a33204 fixes a Bug in which the server only looks at a resource ID and not the resource Type for Read/Vread/DeleteVersion operations.

Can you clarify what you were doing with the create operation prior to the Feb 5th code change? Were you creating new resources with predefined IDs?

-Tim

**Comment by AllanHodkinson** [comment]
Hi Tim,
Yes it is the Update as Create that we would like to use - we'd like the ability to create a resource with a predefined ID.

We were using the create operation to do this with v3.0.0 but moving to v3.2.1 we've now lost this capability (but I agree with the change you've made, as create shouldn't accept a resource with ID, it just took us by surprise when our implementation stopped working!).

Many thanks,
Allan

**Comment by nguyen102** [comment]
We decided to remove "id" from the Create operation to more closely align with FHIR standards.
https://www.hl7.org/fhir/http.html#create

"If the client wishes to have control over the id of a newly submitted resource, it should use the update interaction instead."

To comply to FHIR Standard, implementing support for Update as Create is probably the best next steps. Would you be willing to create a PR to add this feature to FWoA? Our team will gladly work with you in getting this feature implemented.

The change will involve this function
https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/eefb657b0639c10910ada404f91d6418926b339c/src/dataServices/dynamoDbDataService.ts#L154

**Comment by AllanHodkinson** [comment]
Sure, we can take a look at making this change, it doesn't look too complicated.
