### ISSUE TITLE
Support Patch operation

### ISSUE THREAD

**Issue by rsmayda** [awslabs/fhir-works-on-aws-persistence-ddb#6]
Build in support for the patch operation as described by FHIR: https://www.hl7.org/fhir/http.html#patch

A/C:
- Add functionality
- Update integration test
- Update deployment package to support 'patch' as well

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new
features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:aws-security@amazon.com)](mailto:[security@amazon.com](mailto:security@amazon.com)). If you are new to this solution, we advise you to explore using HealthLake (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [[fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com)](mailto:[fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com)) or contact your AWS Account team.
