### ISSUE TITLE
Allow storage of Resource Metadata in the meta element

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-persistence-ddb#60]
Allow storage of Resource Metadata in the meta element:

https://www.hl7.org/fhir/resource.html#Meta

Currently it appears any meta data is replaced with vid and lastUpdated

**Comment by SanketD92** [comment]
Thank you for opening this issue, @medhost-bfindeisen. 

We will be starting work on this requirement soon. Stay tuned!

**Comment by SanketD92** [comment]
@medhost-bfindeisen, meanwhile if you need to work on customizing the code on your dev environment, feel free to add the remaining meta items on the [interface](https://github.com/awslabs/fhir-works-on-aws-interface/blob/3bce87cb9ef96165601b3055f0e0bb929c9c26a5/src/resourceMeta.ts#L24) package and accordingly handle argument passing where it's being used while [creating](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/14a254e7c290b459660506c637de4601a0c36aa8/src/dataServices/dynamoDbDataService.ts#L115) and [updating](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/14a254e7c290b459660506c637de4601a0c36aa8/src/dataServices/dynamoDbDataService.ts#L187) the resource on the persistence package.

For testing your changes locally, please use these [instructions](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/dc9d0beb091263e55ea244f51703041615da03b5/DEVELOPMENT.md) for a smoother development experience.

**Comment by rsmayda** [comment]
Working on this now!
