### ISSUE TITLE
Loss of resource meta data in v3.3.1

### ISSUE THREAD

**Issue by paulschneider** [awslabs/fhir-works-on-aws-persistence-ddb#64]
Updating to the latest version of the package (3.3.0 -> 3.3.1) results in the loss of content in the meta data resource attribute.

In v3.3.0 when updateResource() is called the returned resource (the result of the update operation) contains (for example):

[MedicationRequest]

`
{
  versionId: "2",
  lastUpdated: "2021-04-13T23:10:07.899Z",
}
`

In v3.3.1 when updateResource() is called the returned resource meta attribute contains:

`null`

**Comment by rsmayda** [comment]
Thanks for reporting -- I was able to replicate. We will get this fixed shortly. One thing to note this is a visualization issue, the meta tag is still stored in the DynamoDB and a subsequent GET call will show the new meta tag

**Comment by paulschneider** [comment]
Thanks, @rsmayda - Yes we spotted that a re-read returns the correct metadata. We've locked to v3.3.0 for now to prevent the need for the additional call. 

Just spotted 3.3.2. Awesome work, thank you for the speedy update.
