### ISSUE TITLE
Support resources that are >400kb

### ISSUE THREAD

**Issue by rsmayda** [awslabs/fhir-works-on-aws-persistence-ddb#9]
FHIR resource are currently stored in DynamoDb and Dynamo has a row size limitation of 400kb. Meaning if a user tries to create a Patient record >400kb it will fail. This task is researching & implementing how we can remove this limitation.

A/C:

- Add functionality
- Update integration test

**Comment by rsmayda** [comment]
An idea that has been floated is to compress the json prior to storing it in DDB

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
