### ISSUE TITLE
[Bug] Synchronization of DDB data with ES using the DDB-to-ES lambda is slow

### ISSUE THREAD

**Issue by arnabguptadev** [awslabs/fhir-works-on-aws-persistence-ddb#93]
**Describe the bug**
The synchronization of DynamoDB data to ElasticSearch using the DynamoDB stream is slow and results in large number of errors when the data volume is high.

**To Reproduce**
1. Load a large amount of data in DynamoDB
2. Check the aws cloudwatch console to monitor ElasticSearch
3. The synchronization goes on for a large time with large number of errors.

**Expected behavior**
The synchronization should complete within acceptable time and reduced errors.

**Screenshots**

**Versions (please complete the following information):**
 - 3.4.0

**Additional context**
As discussed with AWS team, using batch update APIs for ElasticSearch may significantly address this issue.

**Comment by carvantes** [comment]
The fix is merged. 

We'll close this issue once we release a new version of this package

**Comment by arnabguptadev** [comment]
Thanks @carvantes! Appreciate it. Will test and ask team to close.

**Comment by rsmayda** [comment]
Merged in as 3.6.1
