### ISSUE TITLE
[Bug] Duplicate records for some resource identifiers in AVAILABLE status

### ISSUE THREAD

**Issue by arnabguptadev** [awslabs/fhir-works-on-aws-persistence-ddb#95]
**Describe the bug**
We run ETL jobs to load data into DynamoDB using the DynamoDbBundleService's [transaction](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/42df1e44c742441142dbde98b2fb8d51d6cf3c0b/src/dataServices/dynamoDbBundleService.ts#L51) method. Our approach involves creating FHIR resources as a bundle, parse them using the BundleParser and then call the above method to persist the contents. One other aspect of our transformation that may be causing this issue is the fact that we load historical data in large volumes and use an algorithm to predictably generate the identifier of the target FHIR resources. That can potentially cause race conditions when the same resource ID of a resource type is being updated from more than one workers (multiple processes implement the ETL).

The present approach of locking seems to be failing here thus causing multiple versions with same resource identifier to have the AVAILABLE status. A side-effect of this is the presence of duplicate records in ElasticSearch as well.

**To Reproduce**
1. Take multiple records with same identifier and simultaneously try to update - preferably from multiple processes.

**Expected behavior**
A locking error should be predictably thrown so the calling code can catch, analyze and retry as needed.

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Additional context**

**Comment by SanketD92** [comment]
Thank you for opening this bug, @arnabguptadev. We have added this to our team's backlog and will work on it based on priority.

**Comment by Bingjiling** [comment]
Hi @arnabguptadev, thanks for reaching out! I'm wondering if you could share the bundle data that can be used to call the transaction method and reproduce this issue? It'll help us greatly in reproducing the issue.

**Comment by Bingjiling** [comment]
Hi @arnabguptadev, thanks for reaching out! 

I tried recreating this issue with this [test](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/race-condition/integration-tests/raceCondition.test.ts) and [bundle request data](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/race-condition/integration-tests/updatePatientsBundle.json), however, I was not able to recreate the issue. All of the three resources updated only has one record in AVAILABLE status after many updates. 

In particular, when the wait time between the two request is equal or less than 2ms, the second request always fail for locking error; and when the wait time is more than 2ms, the two requests both succeed sequentially. I also tried triggering the test from two terminal sessions but I wasn't able to recreate the issue either. 

Could you please provide more information as for how this issue can be recreated? 

Thanks,
Yanyu

**Comment by arnabguptadev** [comment]
Hi @Bingjiling  - I am not working on this anymore. @justinusmenzel, @arthuston or @emilhdiaz may be able to provide more information.
