### ISSUE TITLE
[Feature Request] Need ability to specify index/alias name in handleDdbToEsEvent

### ISSUE THREAD

**Issue by arnabguptadev** [awslabs/fhir-works-on-aws-persistence-ddb#96]
**Is your feature request related to a problem? Please describe.**
Need a way to populate ElasticSearch index without using the standard alias used in AWS Fhirworks DDB to ES Lambda. Since the lambda may fail, we need ways to populate the index with data or even want to rebuild specific indices if needed. Currently the code to do this - [handleDdbToEsEvent](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/42df1e44c742441142dbde98b2fb8d51d6cf3c0b/src/ddbToEs/index.ts#L16) - makes an assumption on the alias name to use. This alias is backed by an index. We want to be able to populate that index independent of the current index that backs the alias. That way, we can reindex and then switch the alias without a downtime. We plan to use the above method - but the assumption made in the code always forces the data to go through a fixed alias name.

**Describe the solution you'd like**
There should be a way to specify the target index in the method handleDdbToEsEvent. This can either be a part of the entries in the event object that is a method parameter or a callback function - that - given a resourceType - can return the index to use.

**Describe alternatives you've considered**
We currently use our code to batch the updates. We do want to use the AWS method once it supports batch.

**Additional context**

**Comment by SanketD92** [comment]
Thank you for opening this feature request, @arnabguptadev. We have added this to our team's backlog and will work on it based on priority.
